In [2]:
import numpy as np 

In [33]:
x = [1,2,4,5,6] 

In [34]:
y = np.matrix(x)

In [39]:
y.shape

(1, 5)

In [36]:
z = y.transpose()

In [40]:
z.shape

(5, 1)

In [43]:
mymat = z*y

In [42]:
print(z)
print(y)

[[1]
 [2]
 [4]
 [5]
 [6]]
[[1 2 4 5 6]]


In [47]:
mymat +  2

matrix([[ 3,  4,  6,  7,  8],
        [ 4,  6, 10, 12, 14],
        [ 6, 10, 18, 22, 26],
        [ 7, 12, 22, 27, 32],
        [ 8, 14, 26, 32, 38]])

In [57]:
mymat * y.transpose()

matrix([[ 82],
        [164],
        [328],
        [410],
        [492]])

In [50]:
mymat

matrix([[ 1,  2,  4,  5,  6],
        [ 2,  4,  8, 10, 12],
        [ 4,  8, 16, 20, 24],
        [ 5, 10, 20, 25, 30],
        [ 6, 12, 24, 30, 36]])